sudo: required
services: 
  - docker

before_install:
  - docker build -t grigol/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true grigol/react-test npm test

after_success:
  - docker build -t grigol/multi-client ./client
  - docker build -t grigol/multi-nginx ./nginx
  - docker build -t grigol/multi-server ./server
  - docker build -t grigol/multi-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Pushing docker images to docker hub
  - docker push grigol/multi-client
  - docker push grigol/multi-nginx
  - docker push grigol/multi-server
  - docker push grigol/multi-worker
